import type { IconType } from 'react-icons';
import {
  TbAdjustments,
  TbAdjustmentsHorizontal,
  TbAlertCircleFilled,
  TbAlertTriangleFilled,
  TbArrowDown,
  TbArrowLeft,
  TbArrowRight,
  TbArrowUp,
  TbBan,
  TbBellFilled,
  TbBoltFilled,
  TbBook2,
  TbBox,
  TbBoxMultiple,
  TbBrandFacebookFilled,
  TbBriefcaseFilled,
  TbBuildingStore,
  TbBuildingWarehouse,
  TbCalendarCheck,
  TbCalendarEventFilled,
  TbCalendarMonthFilled,
  TbCameraFilled,
  TbChartBar,
  TbChartLine,
  TbCheck,
  TbChevronDown,
  TbCircleCheckFilled,
  TbCircleFilled,
  TbCircleMinus,
  TbCircleXFilled,
  TbCloudUpload,
  TbCompassFilled,
  TbCopy,
  TbCreditCardFilled,
  TbClockFilled,
  TbCube,
  TbDeviceFloppy,
  TbDownload,
  TbExclamationCircleFilled,
  TbEye,
  TbEyeOff,
  TbExternalLink,
  TbFileSadFilled,
  TbFileTextFilled,
  TbFlagFilled,
  TbFlameFilled,
  TbFolderMinus,
  TbFolderOpen,
  TbGripVertical,
  TbHelpCircleFilled,
  TbHistory,
  TbHomeFilled,
  TbIdBadge2,
  TbInbox,
  TbInfoCircleFilled,
  TbKeyFilled,
  TbLayersIntersect,
  TbLayoutGridFilled,
  TbLink,
  TbListDetails,
  TbListNumbers,
  TbLockFilled,
  TbLogout2,
  TbMailFilled,
  TbMenu2,
  TbMessageReply,
  TbMessages,
  TbMinus,
  TbPackage,
  TbPackages,
  TbPaletteFilled,
  TbPencil,
  TbPercentage,
  TbPhotoFilled,
  TbPinnedFilled,
  TbPlayerPauseFilled,
  TbPlayerPlayFilled,
  TbPlug,
  TbPlus,
  TbReceiptDollarFilled,
  TbReceiptFilled,
  TbRefresh,
  TbSearch,
  TbSchema,
  TbSend,
  TbSettingsFilled,
  TbShieldFilled,
  TbShirtFilled,
  TbShoppingBag,
  TbShoppingCartFilled,
  TbSparkles,
  TbSpeakerphone,
  TbStar,
  TbStarFilled,
  TbStarHalfFilled,
  TbStopwatch,
  TbTagFilled,
  TbTagsFilled,
  TbTargetArrow,
  TbTicket,
  TbTrashFilled,
  TbTrophyFilled,
  TbTruckFilled,
  TbTruckLoading,
  TbUnlink,
  TbUserCircle,
  TbUserOff,
  TbUserPlus,
  TbUserShield,
  TbUsers,
  TbWallet,
  TbWaveSquare,
  TbWorld,
  TbX,
} from 'react-icons/tb';

interface AdminIconProps {
  name?: string | null;
  className?: string;
}

const ICON_MAP: Record<string, IconType> = {
  'fa-arrow-down': TbArrowDown,
  'fa-arrow-left': TbArrowLeft,
  'fa-arrow-right': TbArrowRight,
  'fa-arrow-up': TbArrowUp,
  'fa-ban': TbBan,
  'fa-bar-chart': TbChartBar,
  'fa-bars': TbMenu2,
  'fa-bell': TbBellFilled,
  'fa-bolt': TbBoltFilled,
  'fa-book-open': TbBook2,
  'fa-box': TbBox,
  'fa-boxes': TbPackages,
  'fa-box-open': TbPackage,
  'fa-briefcase': TbBriefcaseFilled,
  'fa-bullhorn': TbSpeakerphone,
  'fa-bullseye': TbTargetArrow,
  'fa-calendar-alt': TbCalendarMonthFilled,
  'fa-calendar-check': TbCalendarCheck,
  'fa-calendar-days': TbCalendarEventFilled,
  'fa-camera': TbCameraFilled,
  'fa-chart-bar': TbChartBar,
  'fa-chart-line': TbChartLine,
  'fa-check': TbCheck,
  'fa-check-circle': TbCircleCheckFilled,
  'fa-chevron-down': TbChevronDown,
  'fa-chevron-left': TbArrowLeft,
  'fa-chevron-right': TbArrowRight,
  'fa-circle': TbCircleFilled,
  'fa-circle-check': TbCircleCheckFilled,
  'fa-circle-exclamation': TbAlertCircleFilled,
  'fa-circle-info': TbInfoCircleFilled,
  'fa-circle-question': TbHelpCircleFilled,
  'fa-circle-xmark': TbCircleXFilled,
  'fa-clock': TbClockFilled,
  'fa-clock-rotate-left': TbHistory,
  'fa-cloud-upload-alt': TbCloudUpload,
  'fa-cog': TbSettingsFilled,
  'fa-comments': TbMessages,
  'fa-compass': TbCompassFilled,
  'fa-copy': TbCopy,
  'fa-credit-card': TbCreditCardFilled,
  'fa-cube': TbCube,
  'fa-cubes': TbBoxMultiple,
  'fa-diagram-project': TbSchema,
  'fa-dollar-sign': TbReceiptDollarFilled,
  'fa-download': TbDownload,
  'fa-edit': TbPencil,
  'fa-envelope': TbMailFilled,
  'fa-exclamation-circle': TbExclamationCircleFilled,
  'fa-exclamation-triangle': TbAlertTriangleFilled,
  'fa-external-link-alt': TbExternalLink,
  'fa-eye': TbEye,
  'fa-eye-slash': TbEyeOff,
  'fa-facebook': TbBrandFacebookFilled,
  'fa-file-alt': TbFileTextFilled,
  'fa-file-circle-xmark': TbFileSadFilled,
  'fa-fire': TbFlameFilled,
  'fa-flag-checkered': TbFlagFilled,
  'fa-folder-minus': TbFolderMinus,
  'fa-folder-open': TbFolderOpen,
  'fa-globe': TbWorld,
  'fa-grip-vertical': TbGripVertical,
  'fa-history': TbHistory,
  'fa-hourglass-half': TbStopwatch,
  'fa-house': TbHomeFilled,
  'fa-id-card': TbIdBadge2,
  'fa-image': TbPhotoFilled,
  'fa-images': TbPhotoFilled,
  'fa-inbox': TbInbox,
  'fa-info-circle': TbInfoCircleFilled,
  'fa-key': TbKeyFilled,
  'fa-layer-group': TbLayersIntersect,
  'fa-line-chart': TbChartLine,
  'fa-link': TbLink,
  'fa-list': TbListDetails,
  'fa-list-ol': TbListNumbers,
  'fa-lock': TbLockFilled,
  'fa-minus': TbMinus,
  'fa-minus-circle': TbCircleMinus,
  'fa-money': TbWallet,
  'fa-palette': TbPaletteFilled,
  'fa-paper-plane': TbSend,
  'fa-pause': TbPlayerPauseFilled,
  'fa-pen': TbPencil,
  'fa-pen-ruler': TbPencil,
  'fa-percent': TbPercentage,
  'fa-play': TbPlayerPlayFilled,
  'fa-plug': TbPlug,
  'fa-plus': TbPlus,
  'fa-receipt': TbReceiptFilled,
  'fa-refresh': TbRefresh,
  'fa-reply': TbMessageReply,
  'fa-right-from-bracket': TbLogout2,
  'fa-rotate-left': TbRefresh,
  'fa-save': TbDeviceFloppy,
  'fa-search': TbSearch,
  'fa-shield-alt': TbShieldFilled,
  'fa-shirt': TbShirtFilled,
  'fa-shopping-bag': TbShoppingBag,
  'fa-shopping-cart': TbShoppingCartFilled,
  'fa-sign-out-alt': TbLogout2,
  'fa-sliders': TbAdjustments,
  'fa-sliders-h': TbAdjustmentsHorizontal,
  'fa-spinner': TbRefresh,
  'fa-star': TbStarFilled,
  'fa-star-half-o': TbStarHalfFilled,
  'fa-star-half-stroke': TbStarHalfFilled,
  'fa-star-o': TbStar,
  'fa-stopwatch': TbStopwatch,
  'fa-store': TbBuildingStore,
  'fa-stream': TbLayoutGridFilled,
  'fa-tag': TbTagFilled,
  'fa-tags': TbTagsFilled,
  'fa-thumb-tack': TbPinnedFilled,
  'fa-ticket': TbTicket,
  'fa-times': TbX,
  'fa-times-circle': TbCircleXFilled,
  'fa-trash': TbTrashFilled,
  'fa-triangle-exclamation': TbAlertTriangleFilled,
  'fa-trophy': TbTrophyFilled,
  'fa-truck': TbTruckFilled,
  'fa-truck-loading': TbTruckLoading,
  'fa-unlink': TbUnlink,
  'fa-user': TbUserCircle,
  'fa-user-plus': TbUserPlus,
  'fa-users': TbUsers,
  'fa-user-shield': TbUserShield,
  'fa-user-slash': TbUserOff,
  'fa-wallet': TbWallet,
  'fa-warehouse': TbBuildingWarehouse,
  'fa-wave-square': TbWaveSquare,
  'fa-xmark': TbX,
};

const STYLE_TOKENS = new Set(['fa', 'fab', 'far', 'fas']);

function resolveIconName(name?: string | null) {
  if (!name) {
    return { iconName: '', isSpin: false };
  }

  const tokens = name.trim().split(/\s+/).filter(Boolean);
  const isSpin = tokens.includes('fa-spin');
  const iconName = tokens.find((token) => token.startsWith('fa-') && token !== 'fa-spin') || '';

  return { iconName, isSpin };
}

export default function AdminIcon({ name, className }: AdminIconProps) {
  const cleanedName = (name || '')
    .trim()
    .split(/\s+/)
    .filter((token) => !STYLE_TOKENS.has(token))
    .join(' ');
  const { iconName, isSpin } = resolveIconName(cleanedName);
  const IconComponent = (iconName ? ICON_MAP[iconName] : undefined) || TbSparkles;
  const classes = ['admin-icon', className, isSpin ? 'is-spin' : ''].filter(Boolean).join(' ');

  return (
    <i className={classes} aria-hidden="true">
      <IconComponent />
    </i>
  );
}
