// <auto-generated />
using System;
using API.Customer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260326085235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Customer.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QuanHuyen");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("LaMacDinh");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TinhThanh");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiCuThe");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhuongXa");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("API.Customer.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("API.Customer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenDanhMuc");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucChaId");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("API.Customer.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBoSuuTap");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("BoSuuTap");
                });

            modelBuilder.Entity("API.Customer.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaCoupon");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiamToiDa");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonToiThieu");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiGiamGia");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("SoLuotDung");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int")
                        .HasColumnName("DaSuDung");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiaTri");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MaGiamGia");
                });

            modelBuilder.Entity("API.Customer.Models.Lookbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LienKet");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDePhu");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.HasKey("Id");

                    b.ToTable("Lookbook");
                });

            modelBuilder.Entity("API.Customer.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaGiamGia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiGiao");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNguoiNhan");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiamGia");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaDonHang");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("PhiVanChuyen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TamTinh");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongTien");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("API.Customer.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonGia");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnhSP");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSanPham");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("API.Customer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhomTuoi");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhMuc");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int")
                        .HasColumnName("BoSuuTapId");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachMau");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaChiTiet");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachAnh");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit")
                        .HasColumnName("BanChayNhat");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("LaSanPhamMoi");

                    b.Property<bool>("IsSale")
                        .HasColumnType("bit")
                        .HasColumnName("DangGiamGia");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Menu");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetaTitle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSanPham");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiaCu");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Gia");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("DiemDanhGia");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNgan");

                    b.Property<string>("Sizes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachSize");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaSanPham");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Slug");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaBan");

                    b.Property<string>("Specs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThongSoKyThuat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("TonKho");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhongCach");

                    b.Property<string>("Subcategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhMucPhu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("Variants")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BienThe");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("API.Customer.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKhachHang");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("SoSao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("API.Customer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VaiTro");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("API.Customer.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("DanhSachYeuThich");
                });

            modelBuilder.Entity("API.Customer.Models.CartItem", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.OrderItem", b =>
                {
                    b.HasOne("API.Customer.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.Review", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.WishlistItem", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("API.Customer.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
