// <auto-generated />
using System;
using API.Customer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Customer.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260529145249_AddChatTables")]
    partial class AddChatTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Customer.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QuanHuyen");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("LaMacDinh");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TinhThanh");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiCuThe");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhuongXa");

                    b.HasKey("Id");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("API.Customer.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LienKet");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTri");

                    b.Property<string>("PrimaryButton")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NutChinh");

                    b.Property<string>("SecondLink")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkPhu");

                    b.Property<string>("SecondaryButton")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NutPhu");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDePhu");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiBanner");

                    b.HasKey("Id");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("API.Customer.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<DateTime?>("ReservedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("GiuDenLuc");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("API.Customer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenDanhMuc");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("DanhMucChaId");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("API.Customer.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DinhKemJson");

                    b.Property<string>("AttachmentRefId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DinhKemId");

                    b.Property<string>("AttachmentType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiDinhKem");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("CuocHoiThoaiId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("DaDoc");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiGuiId");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiNguoiGui");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Id");

                    b.ToTable("TinNhan");
                });

            modelBuilder.Entity("API.Customer.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBoSuuTap");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.HasKey("Id");

                    b.ToTable("BoSuuTap");
                });

            modelBuilder.Entity("API.Customer.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int")
                        .HasColumnName("NhanVienId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenHienThi");

                    b.Property<string>("GuestId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaKhachVangLai");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianTinCuoi");

                    b.Property<string>("LastMessagePreview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TinNhanCuoi");

                    b.Property<int?>("ProductContextId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamNguCanhId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("UnreadForAgent")
                        .HasColumnType("int")
                        .HasColumnName("SoTinChuaDocNV");

                    b.Property<int>("UnreadForCustomer")
                        .HasColumnType("int")
                        .HasColumnName("SoTinChuaDocKhach");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "LastMessageAt");

                    b.ToTable("CuocHoiThoai");
                });

            modelBuilder.Entity("API.Customer.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaCoupon");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiamToiDa");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonToiThieu");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiGiamGia");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("SoLuotDung");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int")
                        .HasColumnName("DaSuDung");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiaTri");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MaGiamGia");
                });

            modelBuilder.Entity("API.Customer.Models.HomepageBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BlockType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Icon");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LienKet");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDePhu");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("HomepageBlock");
                });

            modelBuilder.Entity("API.Customer.Models.Lookbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LienKet");

                    b.Property<string>("Season")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Season");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Style");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDePhu");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VideoUrl");

                    b.HasKey("Id");

                    b.ToTable("Lookbook");
                });

            modelBuilder.Entity("API.Customer.Models.LookbookHotspot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("LookbookId")
                        .HasColumnType("int")
                        .HasColumnName("LookbookId");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<decimal>("X")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ToaDoX");

                    b.Property<decimal>("Y")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ToaDoY");

                    b.HasKey("Id");

                    b.HasIndex("LookbookId");

                    b.HasIndex("ProductId");

                    b.ToTable("LookbookHotspot");
                });

            modelBuilder.Entity("API.Customer.Models.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DangKyNewsletter");
                });

            modelBuilder.Entity("API.Customer.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("DaDoc");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LienKet");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiThongBao");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("API.Customer.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaGiamGia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiaChiGiao");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNguoiNhan");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiamGia");

                    b.Property<int?>("LeadTimeHours")
                        .HasColumnType("int")
                        .HasColumnName("ThoiGianGiaoDuKien");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MaDonHang");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThanhToan");

                    b.Property<DateTime?>("PaymentExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("HetHanThanhToan");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("PhiVanChuyen");

                    b.Property<string>("ShippingProvider")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhaVanChuyen");

                    b.Property<string>("ShippingServiceCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaDichVuVanChuyen");

                    b.Property<string>("ShippingStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThaiVanChuyen");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TamTinh");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaVanDon");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LinkTracking");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("API.Customer.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("DonGia");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnhSP");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSanPham");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("API.Customer.Models.PointsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int")
                        .HasColumnName("SoDuSauGiaoDich");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("SoDiem");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoaiGiaoDich");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.ToTable("LichSuDiem");
                });

            modelBuilder.Entity("API.Customer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhomTuoi");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhMuc");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int")
                        .HasColumnName("BoSuuTapId");

                    b.Property<string>("Colors")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachMau");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaChiTiet");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachAnh");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit")
                        .HasColumnName("BanChayNhat");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("LaSanPhamMoi");

                    b.Property<bool>("IsSale")
                        .HasColumnType("bit")
                        .HasColumnName("DangGiamGia");

                    b.Property<string>("Menu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Menu");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetaTitle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSanPham");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("GiaCu");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Gia");

                    b.Property<double>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("DiemDanhGia");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNgan");

                    b.Property<string>("Sizes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachSize");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaSanPham");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Slug");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaBan");

                    b.Property<string>("Specs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThongSoKyThuat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("TonKho");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhongCach");

                    b.Property<string>("Subcategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhMucPhu");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("Variants")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BienThe");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("API.Customer.Models.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomThuocTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuocTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThuocTinhSanPham");
                });

            modelBuilder.Entity("API.Customer.Models.ProductQA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TraLoi");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTraLoi");

                    b.Property<string>("AnsweredBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiTraLoi");

                    b.Property<DateTime>("AskedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHoi");

                    b.Property<int?>("AskerId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiHoiId");

                    b.Property<string>("AskerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNguoiHoi");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int")
                        .HasColumnName("LuotHuuIch");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CauHoi");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.ToTable("CauHoiSanPham");
                });

            modelBuilder.Entity("API.Customer.Models.ProductViewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ip");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastSeenAt");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SessionId");

                    b.HasKey("Id");

                    b.ToTable("PhienXemSanPham");
                });

            modelBuilder.Entity("API.Customer.Models.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NewUserCoupon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCouponMoi");

                    b.Property<int>("NewUserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiMoiId");

                    b.Property<string>("ReferrerCoupon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCouponGT");

                    b.Property<int>("ReferrerId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiGioiThieuId");

                    b.Property<DateTime?>("RewardedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThuong");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.ToTable("GioiThieu");
                });

            modelBuilder.Entity("API.Customer.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhanHoiAdmin");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKhachHang");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int")
                        .HasColumnName("LuotHuuIch");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhSachAnh");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("SoSao");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayPhanHoi");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Video");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("API.Customer.Models.ShippingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTri");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("DonHangId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGian");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("LichSuTrangThaiVanChuyen");
                });

            modelBuilder.Entity("API.Customer.Models.SizeChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.Property<int?>("BottomLength")
                        .HasColumnType("int")
                        .HasColumnName("DaiQuan");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhMuc");

                    b.Property<int?>("Chest")
                        .HasColumnType("int")
                        .HasColumnName("Nguc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChieuCao");

                    b.Property<int?>("Hip")
                        .HasColumnType("int")
                        .HasColumnName("Hong");

                    b.Property<int?>("Shoulder")
                        .HasColumnType("int")
                        .HasColumnName("Vai");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenSize");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("ThuTu");

                    b.Property<int?>("TopLength")
                        .HasColumnType("int")
                        .HasColumnName("DaiAo");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Loai");

                    b.Property<int?>("Waist")
                        .HasColumnType("int")
                        .HasColumnName("Eo");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CanNang");

                    b.HasKey("Id");

                    b.ToTable("BangSize");
                });

            modelBuilder.Entity("API.Customer.Models.StoreSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCauHinh");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhomCauHinh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GiaTri");

                    b.HasKey("Id");

                    b.ToTable("CauHinhCuaHang");
                });

            modelBuilder.Entity("API.Customer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int")
                        .HasColumnName("DiemThuong");

                    b.Property<string>("MemberTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CapBac");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaGioiThieu");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VaiTro");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("TongChiTieu");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("API.Customer.Models.VariantStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MauSac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("Reserved")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaGiu");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KichCo");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaBan");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.HasKey("Id");

                    b.ToTable("TonKhoBienThe");
                });

            modelBuilder.Entity("API.Customer.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("SanPhamId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiDungId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("DanhSachYeuThich");
                });

            modelBuilder.Entity("API.Customer.Models.CartItem", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.ChatMessage", b =>
                {
                    b.HasOne("API.Customer.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("API.Customer.Models.LookbookHotspot", b =>
                {
                    b.HasOne("API.Customer.Models.Lookbook", "Lookbook")
                        .WithMany("Hotspots")
                        .HasForeignKey("LookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookbook");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.OrderItem", b =>
                {
                    b.HasOne("API.Customer.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.Review", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.ShippingHistory", b =>
                {
                    b.HasOne("API.Customer.Models.Order", "Order")
                        .WithMany("ShippingHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("API.Customer.Models.WishlistItem", b =>
                {
                    b.HasOne("API.Customer.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("API.Customer.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("API.Customer.Models.Lookbook", b =>
                {
                    b.Navigation("Hotspots");
                });

            modelBuilder.Entity("API.Customer.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ShippingHistories");
                });

            modelBuilder.Entity("API.Customer.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
